### PR TITLE
Expose all formats of a recording

### LINKED ISSUE #66: Get recordings is only returning one playback format
As documented in [getRecordings](https://docs.bigbluebutton.org/dev/api.html#getrecordings), one recording can have multiple playback formats. In [Record.php](https://github.com/littleredbutton/bigbluebutton-api-php/blob/master/src/Core/Record.php) we assume that there is only one element (I'm still wondering why this doesn't crash).

```xml
<recording>
         <recordID>ffbfc4cc24428694e8b53a4e144f414052431693-1530718721124</recordID>
         <meetingID>c637ba21adcd0191f48f5c4bf23fab0f96ed5c18</meetingID>
         <internalMeetingID>ffbfc4cc24428694e8b53a4e144f414052431693-1530718721124</internalMeetingID>
         <name>Fred's Room</name>
         <isBreakout>false</isBreakout>
         <published>true</published>
         <state>published</state>
         <startTime>1530718721124</startTime>
         <endTime>1530718810456</endTime>
         <participants>3</participants>
         <metadata>
            <isBreakout>false</isBreakout>
            <meetingName>Fred's Room</meetingName>
            <gl-listed>false</gl-listed>
            <meetingId>c637ba21adcd0191f48f5c4bf23fab0f96ed5c18</meetingId>
         </metadata>
         <playback>
            <format>
               <type>podcast</type>
               <url>https://demo.bigbluebutton.org/podcast/ffbfc4cc24428694e8b53a4e144f414052431693-1530718721124/audio.ogg</url>
               <processingTime>0</processingTime>
               <length>0</length>
            </format>
            <format>
               <type>presentation</type>
               <url>https://demo.bigbluebutton.org/playback/presentation/2.0/playback.html?meetingId=ffbfc4cc24428694e8b53a4e144f414052431693-1530718721124</url>
               <processingTime>7177</processingTime>
               <length>0</length>
               <preview>
                  <images>
                     <image alt="Welcome to" height="136" width="176">https://demo.bigbluebutton.org/presentation/ffbfc4cc24428694e8b53a4e144f414052431693-1530718721124/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1530718721134/thumbnails/thumb-1.png</image>
                     <image alt="(this slide left blank for use as a whiteboard)" height="136" width="176">https://demo.bigbluebutton.org/presentation/ffbfc4cc24428694e8b53a4e144f414052431693-1530718721124/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1530718721134/thumbnails/thumb-2.png</image>
                     <image alt="(this slide left blank for use as a whiteboard)" height="136" width="176">https://demo.bigbluebutton.org/presentation/ffbfc4cc24428694e8b53a4e144f414052431693-1530718721124/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1530718721134/thumbnails/thumb-3.png</image>
                  </images>
               </preview>
            </format>
         </playback>
</recording>
```

https://github.com/littleredbutton/bigbluebutton-api-php/blob/87c506564ce881836f4dba2307458a95dc5ed320/src/Core/Record.php#L54-L56

### PR DESCRIPTION
**Pull request by sualko**
This pr provides a way to access all available playback formats of a recording. To not break anything, I keep the existing API as a shortcut to quickly access the first format. Does someone have an idea how this could be documented? Is it enough to write it into the method description?

Another thing is that all previews are converted to an array which is maybe not the most elegant solution. What do you think? Should this also wrapped into a class?

fix #66

### CODE REVIEW

**Comment by SamuelWei** [comment]
> This pr provides a way to access all available playback formats of a recording. To not break anything, I keep the existing API as a shortcut to quickly access the first format. Does someone have an idea how this could be documented? Is it enough to write it into the method description?

What about deprecating the getters of the url and length and removing in the next major release?

> Another thing is that all previews are converted to an array which is maybe not the most elegant solution. What do you think? Should this also wrapped into a class?

We could lazy load the preview images, by only creating the array if the getImagePreviews method is called and cache the result for future calls. 

Pseudo code, not tested
```php
    /** @var \SimpleXMLElement */
    private $previewImagesRaw;

    /** @var array */
    private $imagePreviews = null;

    public function __construct(\SimpleXMLElement $xml)
    {
        ...
        $this->previewImagesRaw = $xml->preview->images;
    }

    public function hasImagePreviews(): bool
    {
        return return (bool) $this->previewImagesRaw;
    }

    public function getImagePreviews(): array
    {
        if($this->imagePreviews!=null)
                return $this->imagePreviews;

        if ($this->previewImagesRaw) {
            $this->imagePreviews = [];

            foreach ($this->previewImagesRaw->children() as $image) {
                $attributes = $image->attributes();

                $this->imagePreviews[] = [
                'width'  => (int) $attributes->width->__toString(),
                'height' => (int) $attributes->height->__toString(),
                'alt'    => $attributes->alt->__toString(),
                'url'    => $image->__toString(),
            ];
            }
        }
    }
```

**Comment by sualko** [comment]
> What about deprecating the getters of the url and length and removing in the next major release?

That would be another possibility. Maybe the easiest thing to do.

> We could lazy load the preview images, by only creating the array if the getImagePreviews method is called

I think this is a good enhancement and I will add asap, but my question was more if we should use a wrapper similar to the `PlaybackFormat` class. In my opinion it's maybe a bit too much, but I'm not sure.

**Comment by SamuelWei** [comment]
> I think this is a good enhancement and I will add asap, but my question was more if we should use a wrapper similar to the `PlaybackFormat` class. In my opinion it's maybe a bit too much, but I'm not sure.

Have a look at #110. Just a quick idea how to use the same technique for other properties like `playbackFormats`

**Comment by sualko** [comment]
If we look at other response classes like [CreateMeetingResponse](https://github.com/littleredbutton/bigbluebutton-api-php/blob/master/src/Responses/CreateMeetingResponse.php) the properties are not cached and maybe therefore we should do the same in `PlaybackFormat`.

File: src/Core/PlaybackFormat.php [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+    public function hasImagePreviews(): bool
+    {
+        return !!$this->imagePreviewsRaw;
+    }
+
+    /**
+     *
+     * @return array<int, array{width: int, height: int, alt: string, url: string}>
+     */
+    public function getImagePreviews(): array
```
Comment (FelixJacobi) [inline src/Core/PlaybackFormat.php:83]: Instead of a set of associative arrays, we could create a set of `ImagePreview` objects here. This would improve the usability, typing and interface very much:

~~~php
class ImagePreview
{
    private $width;
    private [...];
}
~~~

With respective getters, of course. The class would take all properties only via constructor and would immutable afterwards, i.e. having only the (typed) getters.

**Review by FelixJacobi — CHANGES_REQUESTED** [review]

File: src/Core/PlaybackFormat.php (hunk 1 above)
Comment (sualko) [reply src/Core/PlaybackFormat.php:83]: That was what I was taking about :smile:. Just thought it's maybe a bit overkill, but yeah you are right, the readability will benefit from wrapping it into classes.

Comment (SamuelWei) [reply src/Core/PlaybackFormat.php:83]: @sualko Any progress?

Comment (FelixJacobi) [reply src/Core/PlaybackFormat.php:83]: > That was what I was taking about smile. Just thought it's maybe a bit overkill, but yeah you are right, the readability will benefit from wrapping it into classes.

There is a simple rule: You can never have enough data objects in your code ;) .

Comment (FelixJacobi) [reply src/Core/PlaybackFormat.php:83]: @sualko If you haven't the time now, I would be happy and to finish here by resolving this discussion. Would that be fine for you?

Comment (sualko) [reply src/Core/PlaybackFormat.php:83]: @FelixJacobi thanks for the offer. I just implemented it by myself :smile:. This means we can probably merge it.

**Review by FelixJacobi — CHANGES_REQUESTED** [review]
Sorry, but forgot that two one in the first iteration, I guess :/ .

**Review by FelixJacobi — APPROVED** [review]
